/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.Register;

import javax.swing.JOptionPane;

/**
 *
 * @author KIATS
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        rePasswordInput = new javax.swing.JPasswordField();
        passwordInput = new javax.swing.JPasswordField();
        surnameLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        rePasswordLabel = new javax.swing.JLabel();
        surnameInput = new javax.swing.JTextField();
        emailLebel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        registerHead = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        registerButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(410, 450, 100, 40);

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        nameLabel.setText("Name");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(310, 130, 140, 40);
        getContentPane().add(rePasswordInput);
        rePasswordInput.setBounds(460, 370, 220, 40);
        getContentPane().add(passwordInput);
        passwordInput.setBounds(460, 310, 220, 40);

        surnameLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        surnameLabel.setText("Surname");
        getContentPane().add(surnameLabel);
        surnameLabel.setBounds(310, 190, 140, 40);
        getContentPane().add(nameInput);
        nameInput.setBounds(460, 130, 220, 40);

        rePasswordLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rePasswordLabel.setText("Re-password");
        getContentPane().add(rePasswordLabel);
        rePasswordLabel.setBounds(310, 370, 140, 40);
        getContentPane().add(surnameInput);
        surnameInput.setBounds(460, 190, 220, 40);

        emailLebel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        emailLebel.setText("Username");
        getContentPane().add(emailLebel);
        emailLebel.setBounds(310, 250, 140, 40);
        getContentPane().add(usernameInput);
        usernameInput.setBounds(460, 250, 220, 40);

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(310, 310, 140, 40);

        registerHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/REgister.PNG"))); // NOI18N
        getContentPane().add(registerHead);
        registerHead.setBounds(0, 0, 1200, 110);

        closeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(540, 450, 100, 40);

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(1000, 500);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        RegisterService RegService = new RegisterService();
        if(nameInput.getText().contains(" ") || surnameInput.getText().contains(" ")
                || usernameInput.getText().contains(" ") || passwordInput.getText().contains(" ")
                || rePasswordInput.getText().contains(" ")){
            JOptionPane.showMessageDialog(null, "Please input our information");
        }else if (!passwordInput.getText().equals(rePasswordInput.getText())){
            JOptionPane.showMessageDialog(null, "Password is not the same.");
        }else if (RegService.checkUsername(usernameInput.getText())){
            JOptionPane.showMessageDialog(null, "Duplicate Username.");
        }else{
            RegService.addUser(usernameInput.getText(),nameInput.getText(),surnameInput.getText(),passwordInput.getText());
            JOptionPane.showMessageDialog(null, "Complete Register.");
             this.dispose();
        }
       
    }//GEN-LAST:event_registerButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel emailLebel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField rePasswordInput;
    private javax.swing.JLabel rePasswordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerHead;
    private javax.swing.JTextField surnameInput;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
