package bookstore.Bill;

import bookstore.CartBook.CartBook;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BUBU
 */
public class Bill extends javax.swing.JFrame{

    ArrayList<String> bookName = new ArrayList<String>();
    ArrayList<String> num = new ArrayList<String>();
    ArrayList<String> price = new ArrayList<String>();
    String item;
    int total;
    DefaultTableModel tableModel;
    
    public Bill(ArrayList<String> bookName, ArrayList<String> num, ArrayList<String> price,int total) {
        initComponents();
        this.bookName = bookName;
        this.num = num;
        this.price = price;
        this.total = total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        billHead = new javax.swing.JLabel();
        shopLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        receiptLabel = new javax.swing.JLabel();
        shopDetail = new javax.swing.JLabel();
        dateDetail = new javax.swing.JLabel();
        receiptDetail = new javax.swing.JLabel();
        comfirmButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        bahtLabel = new javax.swing.JLabel();
        tableScroll = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        totalPriceField = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ใบเสร็จ");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        billHead.setDisplayedMnemonic('o');
        billHead.setFont(new java.awt.Font("AngsanaUPC", 1, 75)); // NOI18N
        billHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Bill.PNG"))); // NOI18N
        billHead.setText("Bill");
        getContentPane().add(billHead);
        billHead.setBounds(0, 0, 1000, 100);

        shopLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        shopLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        shopLabel.setText("Shop");
        getContentPane().add(shopLabel);
        shopLabel.setBounds(60, 120, 80, 19);

        dateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateLabel.setText("Date");
        getContentPane().add(dateLabel);
        dateLabel.setBounds(60, 150, 80, 19);

        receiptLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        receiptLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptLabel.setText("Receipt ID");
        getContentPane().add(receiptLabel);
        receiptLabel.setBounds(60, 180, 80, 19);

        shopDetail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        shopDetail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shopDetail.setText("Book Shop");
        getContentPane().add(shopDetail);
        shopDetail.setBounds(170, 120, 577, 19);

        dateDetail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dateDetail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateDetail.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateDetailAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(dateDetail);
        dateDetail.setBounds(160, 150, 577, 20);

        receiptDetail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        receiptDetail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        receiptDetail.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                receiptDetailAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(receiptDetail);
        receiptDetail.setBounds(170, 180, 577, 20);

        comfirmButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comfirmButton.setText("Confirm");
        comfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(comfirmButton);
        comfirmButton.setBounds(860, 480, 130, 40);

        totalLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalLabel.setText("Total");
        getContentPane().add(totalLabel);
        totalLabel.setBounds(740, 420, 34, 19);

        bahtLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bahtLabel.setText("Baht");
        getContentPane().add(bahtLabel);
        bahtLabel.setBounds(890, 420, 32, 19);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book name", "Amount", "Price"
            }
        ));
        productTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                productTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableScroll.setViewportView(productTable);

        getContentPane().add(tableScroll);
        tableScroll.setBounds(70, 210, 850, 200);

        totalPriceField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalPriceField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPriceField.setText(" ");
        totalPriceField.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                totalPriceFieldAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(totalPriceField);
        totalPriceField.setBounds(783, 420, 100, 19);

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateDetailAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateDetailAncestorAdded
                setTime();
   
    }//GEN-LAST:event_dateDetailAncestorAdded

    private void setTime() {
        long t;
        t = System.currentTimeMillis();
        Date d = new Date(t);
        String s;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        s = sdf.format(d);
        dateDetail.setText("  "+s);
    }

    private void productTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_productTableAncestorAdded
        setBillTable();
        
    }//GEN-LAST:event_productTableAncestorAdded

    private void setBillTable() {
        String[] tblHead = {"Book Name", "Number of book", "Price"};
        tableModel = new DefaultTableModel(tblHead, 0);
        
        for (int i = 0; i < bookName.size(); i++) {
            String[] item = {bookName.get(i), num.get(i), price.get(i)};
            tableModel.addRow(item);
        }
        
        productTable.setModel(tableModel);
    }

    private void totalPriceFieldAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_totalPriceFieldAncestorAdded
        setTotal();
    }//GEN-LAST:event_totalPriceFieldAncestorAdded

    private void setTotal() {
        totalPriceField.setText(total+"");
    }

    private void receiptDetailAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_receiptDetailAncestorAdded
        billId();
    }//GEN-LAST:event_receiptDetailAncestorAdded

    private void billId() {
        int billId = new bookstore.Bill.BillDAO().getBillId();
        setBillId(billId);
    }

    private void setBillId(int billId) {
        receiptDetail.setText(""+billId);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(1000, 530);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void comfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Complete.");
        new bookstore.Bill.BillService().addBillToDatabase(bookName, num, price, total);
        new bookstore.Bill.BillService().removeCart();
        new bookstore.Bill.BillService().updateStock(bookName,num);
        this.setVisible(false);
    }//GEN-LAST:event_comfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {               
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bahtLabel;
    private javax.swing.JLabel billHead;
    private javax.swing.JButton comfirmButton;
    private javax.swing.JLabel dateDetail;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel receiptDetail;
    private javax.swing.JLabel receiptLabel;
    private javax.swing.JLabel shopDetail;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalPriceField;
    // End of variables declaration//GEN-END:variables
}
