/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.Detail;

import bookstore.Book.Book;
import bookstore.Database.User;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author N A T M A N
 */
public class DetailBook extends javax.swing.JFrame {

    /**
     * Creates new form detailBook
     */
    public DetailBook() {
        initComponents();
        this.setSize(1000, 540);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addToCart = new javax.swing.JButton();
        close = new javax.swing.JButton();
        numberSpinner = new javax.swing.JSpinner();
        publisherLabel = new javax.swing.JLabel();
        writerLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        orderNumLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        numPageLabel = new javax.swing.JLabel();
        printLabel = new javax.swing.JLabel();
        publishYearLabel = new javax.swing.JLabel();
        bookImg = new javax.swing.JLabel();
        bookNameLabel = new javax.swing.JLabel();
        publishYearField = new javax.swing.JLabel();
        publisherField = new javax.swing.JLabel();
        writerField = new javax.swing.JLabel();
        typeBookField = new javax.swing.JLabel();
        priceField = new javax.swing.JLabel();
        amountField = new javax.swing.JLabel();
        isbnField = new javax.swing.JLabel();
        numPageField = new javax.swing.JLabel();
        writeNumField = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        addToCart.setText("add to cart");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });
        getContentPane().add(addToCart);
        addToCart.setBounds(770, 480, 110, 40);

        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(890, 480, 100, 40);

        numberSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(numberSpinner);
        numberSpinner.setBounds(850, 400, 80, 30);

        publisherLabel.setText("Publisher");
        getContentPane().add(publisherLabel);
        publisherLabel.setBounds(390, 130, 70, 30);

        writerLabel.setText("Writer");
        getContentPane().add(writerLabel);
        writerLabel.setBounds(390, 180, 70, 30);

        typeLabel.setText("Type");
        getContentPane().add(typeLabel);
        typeLabel.setBounds(390, 230, 70, 30);

        priceLabel.setText("Price");
        getContentPane().add(priceLabel);
        priceLabel.setBounds(390, 280, 70, 30);

        statusLabel.setText("Status");
        getContentPane().add(statusLabel);
        statusLabel.setBounds(390, 330, 70, 30);

        orderNumLabel.setText("Order number");
        getContentPane().add(orderNumLabel);
        orderNumLabel.setBounds(750, 400, 90, 30);

        isbnLabel.setText("ISBN");
        getContentPane().add(isbnLabel);
        isbnLabel.setBounds(640, 130, 120, 30);

        numPageLabel.setText("Number of pages");
        getContentPane().add(numPageLabel);
        numPageLabel.setBounds(640, 180, 120, 30);

        printLabel.setText("Print");
        getContentPane().add(printLabel);
        printLabel.setBounds(640, 230, 120, 30);

        publishYearLabel.setText("Published year");
        getContentPane().add(publishYearLabel);
        publishYearLabel.setBounds(640, 280, 120, 30);

        bookImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookImg.setToolTipText("");
        getContentPane().add(bookImg);
        bookImg.setBounds(40, 70, 270, 350);

        bookNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        bookNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookNameLabel.setText("bookName");
        bookNameLabel.setEnabled(false);
        getContentPane().add(bookNameLabel);
        bookNameLabel.setBounds(0, 40, 1000, 50);

        publishYearField.setText("1");
        getContentPane().add(publishYearField);
        publishYearField.setBounds(790, 280, 110, 30);

        publisherField.setText("1");
        getContentPane().add(publisherField);
        publisherField.setBounds(480, 130, 120, 30);

        writerField.setText("1");
        getContentPane().add(writerField);
        writerField.setBounds(480, 180, 120, 30);

        typeBookField.setText("1");
        getContentPane().add(typeBookField);
        typeBookField.setBounds(480, 230, 120, 30);

        priceField.setText("1");
        getContentPane().add(priceField);
        priceField.setBounds(480, 280, 120, 30);

        amountField.setText("1");
        getContentPane().add(amountField);
        amountField.setBounds(480, 330, 120, 30);

        isbnField.setText("1");
        getContentPane().add(isbnField);
        isbnField.setBounds(790, 130, 110, 30);

        numPageField.setText("1");
        getContentPane().add(numPageField);
        numPageField.setBounds(790, 180, 110, 30);

        writeNumField.setText("1");
        getContentPane().add(writeNumField);
        writeNumField.setBounds(790, 230, 110, 30);

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 540);

        frame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(frame);
        frame.setBounds(350, 100, 580, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        checkLoginIsSuccess();
    }//GEN-LAST:event_addToCartActionPerformed

    public void checkLoginIsSuccess() {
        if(DetailBookService.checkLogin()){
            DetailBookService detail = new DetailBookService();
            String numOrder = numberSpinner.getValue().toString();
            detail.addToCart(User.getName() ,Book.getName(), numOrder, Book.getPrice());
        }
    }

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        closeThisPage();
    }//GEN-LAST:event_closeActionPerformed

    public void closeThisPage() {
        this.setVisible(false);
    }
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart;
    private javax.swing.JLabel amountField;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bookImg;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JButton close;
    private javax.swing.JLabel frame;
    private javax.swing.JLabel isbnField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JLabel numPageField;
    private javax.swing.JLabel numPageLabel;
    private javax.swing.JSpinner numberSpinner;
    private javax.swing.JLabel orderNumLabel;
    private javax.swing.JLabel priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel printLabel;
    private javax.swing.JLabel publishYearField;
    private javax.swing.JLabel publishYearLabel;
    private javax.swing.JLabel publisherField;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel typeBookField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel writeNumField;
    private javax.swing.JLabel writerField;
    private javax.swing.JLabel writerLabel;
    // End of variables declaration//GEN-END:variables

    
    public void openProductDetailUi (String idBook) {
    
        DetailBookService detailBookService = new DetailBookService();
        detailBookService.setProductDetail(idBook);
        
        ImageIcon icon = new ImageIcon(".\\src\\Pic\\Book\\" + Book.getId() + ".jpg");
        Image scaleImage = icon.getImage().getScaledInstance(200, 250, Image.SCALE_DEFAULT);
        bookImg.setIcon(new javax.swing.ImageIcon(scaleImage));
        
        bookNameLabel.setText(Book.getName());
        publisherField.setText(Book.getPublisher());
        writerField.setText(Book.getWriter());
        priceField.setText(Book.getPrice());
        typeBookField.setText(Book.getType());
        publishYearField.setText(Book.getWriteyear());
        isbnField.setText(Book.getISBN());
        writeNumField.setText(Book.getWritenum());
        numPageField.setText(Book.getPage());
         
        if( Integer.parseInt(Book.getAmount()) > 0 ) {
             amountField.setText("In stock.");
        }
        else {
             amountField.setText("Out of stock.");
        }
        
        this.setVisible(true);
    }
}
