/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore;

import bookstore.AllBook.AllBook;
import bookstore.Book.Book;
import bookstore.Book.BookDAO;
import bookstore.Detail.DetailBook;
import bookstore.Book.BookService;
import bookstore.CartBook.CartBook;
import bookstore.Database.User;
import bookstore.Register.Register;
import bookstore.Login.LoginService;
import bookstore.SearchBook.SearchBook;
import bookstore.SearchBook.SearchBookService;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoDatabase;
import java.awt.HeadlessException;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.Timer;

/**
 *
 * @author dell
 */
public class Main extends javax.swing.JFrame {

    static int timesec = 0, timer = 0;
    public static String idBook1 = "1", idBook2 = "2", idBook3 = "3", idBook4 = "4";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blackTab = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchText = new javax.swing.JLabel();
        cartButton = new javax.swing.JLabel();
        searchBox = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        searchLeft = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        searchRight = new javax.swing.JTextField();
        banner2 = new javax.swing.JLabel();
        bookImg4 = new javax.swing.JLabel();
        bookImg3 = new javax.swing.JLabel();
        bookImg2 = new javax.swing.JLabel();
        bookImg1 = new javax.swing.JLabel();
        recommendBook = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        allBookButton = new javax.swing.JLabel();
        bookName4 = new javax.swing.JLabel();
        priceBook4 = new javax.swing.JLabel();
        priceBook3 = new javax.swing.JLabel();
        bookName3 = new javax.swing.JLabel();
        bookName2 = new javax.swing.JLabel();
        priceBook2 = new javax.swing.JLabel();
        priceBook1 = new javax.swing.JLabel();
        bookName1 = new javax.swing.JLabel();
        logInButton = new javax.swing.JLabel();
        registerButton = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        Banner1 = new javax.swing.JLabel();
        banner1 = new javax.swing.JLabel();
        banner3 = new javax.swing.JLabel();
        banner3Label = new javax.swing.JLabel();
        shopIcon = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        blackTab.setBackground(new java.awt.Color(0, 0, 0));
        blackTab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        blackTab.setLayout(null);

        searchPanel.setBackground(new java.awt.Color(0, 0, 0));
        searchPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchPanel.setForeground(new java.awt.Color(255, 51, 51));
        searchPanel.setLayout(null);

        searchText.setFont(new java.awt.Font("Cloud", 1, 14)); // NOI18N
        searchText.setForeground(new java.awt.Color(255, 255, 255));
        searchText.setText("Search");
        searchPanel.add(searchText);
        searchText.setBounds(10, 0, 70, 30);

        blackTab.add(searchPanel);
        searchPanel.setBounds(210, 0, 80, 30);

        cartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/cartButton.png"))); // NOI18N
        cartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartButtonMouseClicked(evt);
            }
        });
        blackTab.add(cartButton);
        cartButton.setBounds(1070, 0, 40, 30);

        searchBox.setBackground(new java.awt.Color(153, 153, 153));
        searchBox.setFont(new java.awt.Font("Cloud", 1, 14)); // NOI18N
        searchBox.setForeground(new java.awt.Color(255, 255, 255));
        searchBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Writer" }));
        searchBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        blackTab.add(searchBox);
        searchBox.setBounds(90, 0, 120, 30);

        searchField.setFont(new java.awt.Font("Cloud", 1, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(153, 153, 153));
        searchField.setText("-Type to search-");
        searchField.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });
        blackTab.add(searchField);
        searchField.setBounds(310, 0, 560, 30);

        searchLeft.setFont(new java.awt.Font("Cloud", 0, 14)); // NOI18N
        searchLeft.setForeground(new java.awt.Color(153, 153, 153));
        searchLeft.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        searchLeft.setEnabled(false);
        blackTab.add(searchLeft);
        searchLeft.setBounds(290, 0, 30, 30);

        search.setBackground(new java.awt.Color(255, 0, 0));
        search.setFont(new java.awt.Font("Cloud", 1, 14)); // NOI18N
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        blackTab.add(search);
        search.setBounds(910, 0, 110, 30);

        searchRight.setFont(new java.awt.Font("Cloud", 0, 14)); // NOI18N
        searchRight.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        searchRight.setEnabled(false);
        blackTab.add(searchRight);
        searchRight.setBounds(860, 0, 30, 30);

        getContentPane().add(blackTab);
        blackTab.setBounds(0, 110, 1220, 30);

        banner2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banner2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Pro1.PNG"))); // NOI18N
        getContentPane().add(banner2);
        banner2.setBounds(970, 350, 210, 220);

        bookImg4.setBackground(new java.awt.Color(0, 0, 0));
        bookImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Book/5.jpg"))); // NOI18N
        bookImg4.setText("4");
        bookImg4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookImg4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProductDetail4(evt);
            }
        });
        getContentPane().add(bookImg4);
        bookImg4.setBounds(690, 460, 120, 160);

        bookImg3.setBackground(new java.awt.Color(0, 0, 0));
        bookImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Book/9.jpg"))); // NOI18N
        bookImg3.setText("3");
        bookImg3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookImg3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProductDetail3(evt);
            }
        });
        getContentPane().add(bookImg3);
        bookImg3.setBounds(480, 460, 120, 160);

        bookImg2.setBackground(new java.awt.Color(0, 0, 0));
        bookImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Book/3.jpg"))); // NOI18N
        bookImg2.setText("2");
        bookImg2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookImg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProductDetail2(evt);
            }
        });
        getContentPane().add(bookImg2);
        bookImg2.setBounds(270, 460, 120, 160);

        bookImg1.setBackground(new java.awt.Color(0, 0, 0));
        bookImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Book/12.jpg"))); // NOI18N
        bookImg1.setText("1");
        bookImg1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookImg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProductDetail1(evt);
            }
        });
        getContentPane().add(bookImg1);
        bookImg1.setBounds(60, 460, 120, 160);

        recommendBook.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        recommendBook.setText("Recommend Books");
        getContentPane().add(recommendBook);
        recommendBook.setBounds(10, 420, 230, 40);

        banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/NewBook.jpg"))); // NOI18N
        getContentPane().add(banner);
        banner.setBounds(60, 150, 790, 270);

        allBookButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        allBookButton.setForeground(new java.awt.Color(255, 0, 0));
        allBookButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allBookButton.setText("View more products");
        allBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allBookButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allBookButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allBookButtonMouseExited(evt);
            }
        });
        getContentPane().add(allBookButton);
        allBookButton.setBounds(700, 430, 150, 20);

        bookName4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bookName4.setText("ไม่พบข้อมูล");
        getContentPane().add(bookName4);
        bookName4.setBounds(690, 640, 170, 19);

        priceBook4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        priceBook4.setText("ไม่พบข้อมูล");
        getContentPane().add(priceBook4);
        priceBook4.setBounds(690, 670, 120, 19);

        priceBook3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        priceBook3.setText("ไม่พบข้อมูล");
        getContentPane().add(priceBook3);
        priceBook3.setBounds(480, 670, 120, 19);

        bookName3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bookName3.setText("ไม่พบข้อมูล");
        getContentPane().add(bookName3);
        bookName3.setBounds(480, 640, 170, 19);

        bookName2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bookName2.setText("ไม่พบข้อมูล");
        getContentPane().add(bookName2);
        bookName2.setBounds(270, 640, 170, 19);

        priceBook2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        priceBook2.setText("ไม่พบข้อมูล");
        getContentPane().add(priceBook2);
        priceBook2.setBounds(270, 670, 120, 19);

        priceBook1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        priceBook1.setText("ไม่พบข้อมูล");
        getContentPane().add(priceBook1);
        priceBook1.setBounds(60, 670, 120, 19);

        bookName1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bookName1.setText("ไม่พบข้อมูล");
        getContentPane().add(bookName1);
        bookName1.setBounds(60, 640, 170, 19);

        logInButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logInButton.setText("Login");
        logInButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInButtonMouseClicked(evt);
            }
        });
        getContentPane().add(logInButton);
        logInButton.setBounds(1120, 30, 70, 20);

        registerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerButton.setText("Register");
        registerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(1120, 60, 70, 20);

        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(1120, 30, 70, 60);

        passLabel.setText("Password");
        getContentPane().add(passLabel);
        passLabel.setBounds(900, 50, 58, 44);

        userLabel.setText("Username");
        getContentPane().add(userLabel);
        userLabel.setBounds(900, 20, 59, 44);
        getContentPane().add(userField);
        userField.setBounds(970, 24, 130, 30);

        statusLabel.setBackground(new java.awt.Color(255, 255, 255));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(statusLabel);
        statusLabel.setBounds(870, 20, 240, 80);
        getContentPane().add(passField);
        passField.setBounds(970, 60, 130, 30);
        getContentPane().add(Banner1);
        Banner1.setBounds(50, 140, 790, 290);

        banner1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banner1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Deal 20-80.png"))); // NOI18N
        getContentPane().add(banner1);
        banner1.setBounds(990, 190, 170, 170);

        banner3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Freetran.png"))); // NOI18N
        getContentPane().add(banner3);
        banner3.setBounds(960, 570, 220, 70);

        banner3Label.setBackground(new java.awt.Color(204, 204, 204));
        banner3Label.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        banner3Label.setForeground(new java.awt.Color(153, 153, 153));
        banner3Label.setText("ติดต่อสอบถาม 0 2826 8753 4");
        getContentPane().add(banner3Label);
        banner3Label.setBounds(1010, 640, 160, 16);

        shopIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Document 9.png"))); // NOI18N
        getContentPane().add(shopIcon);
        shopIcon.setBounds(10, 10, 110, 90);

        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/exitButton2.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(1180, 0, 20, 20);

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(background);
        background.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        searchField.setText("");
    }//GEN-LAST:event_searchFieldMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       if (checkBookIfFound()){
           openSearchUi();
       }
        
    }//GEN-LAST:event_searchActionPerformed

    public boolean checkBookIfFound(){
        if ( !searchField.getText().equals("") && !searchField.getText().contains("-Type to search-")) {
            int countBook = SearchBookService.getBookName(searchBox.getSelectedItem().toString().toLowerCase(),
                    searchField.getText());
            
            if ( countBook != 0 ) {   
               return true;
            }
            else {
                JOptionPane.showMessageDialog( null, "Book Not Found." );
                return false;
            }
        }
        else {
            JOptionPane.showMessageDialog( null, "Please enter a text.");
            return false;
        }
    }
    public void openSearchUi() throws HeadlessException { 
        SearchBook searchBook = new SearchBook();
        searchBook.setTextSearch(searchBox.getSelectedItem().toString().toLowerCase(), searchField.getText());
        searchBook.setVisible(true);
    }

    private void allBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBookButtonMouseClicked
        AllBook allBook = new AllBook();
        allBook.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_allBookButtonMouseClicked

    private void allBookButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBookButtonMouseEntered
        allBookButton.setText("<HTML><U>View more products.</U></HTML>");
    }//GEN-LAST:event_allBookButtonMouseEntered

    private void allBookButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBookButtonMouseExited
        allBookButton.setText("View more products.");
    }//GEN-LAST:event_allBookButtonMouseExited

    private void logInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInButtonMouseClicked
        String check = " ";
        check = LoginService.checkUser(userField.getText(), passField.getText());
        
        if (check.equals("admin") || check.equals("user") && !check.equals("")) {
          
            setUser(check);
            User.setStatus();
            logoutButton.setVisible(true);
            logInButton.setVisible(false);
            registerButton.setVisible(false);
        }
        else if (userField.getText().equals("") || passField.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Please enter a text.");
            
        }
        else {
          
            JOptionPane.showMessageDialog(null, "Can't find user in database.");
        }
        

    }//GEN-LAST:event_logInButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(1200, 700);
        this.setLocationRelativeTo(null);
        
        if (User.getName().equals("")){
            logoutButton.setVisible(false);
        }
        else {
            statusLabel.setText(User.getName());
            statusLabel.setVisible(true);
            userLabel.setVisible(false);
            userField.setVisible(false);
            passLabel.setVisible(false);
            passField.setVisible(false);
            logInButton.setVisible(false);
            registerButton.setVisible(false);
        }
        if (timer == 0){
        time();
        }
        showBook();
        
    }//GEN-LAST:event_formWindowOpened

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        logoutButton.setVisible(false);
        logInButton.setVisible(true);
        registerButton.setVisible(true);
        User.setUser("", "", "");
        statusLabel.setText("");
        statusLabel.setVisible(true);
        userLabel.setVisible(true);
        userField.setVisible(true);
        passLabel.setVisible(true);
        passField.setVisible(true);
        userField.setText("");
        passField.setText("");
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        Register register = new Register();
        register.setVisible(true);
        
    }//GEN-LAST:event_registerButtonMouseClicked

    private void showProductDetail1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProductDetail1
        DetailBook detailBook = new DetailBook();
        detailBook.openProductDetailUi(idBook1);  
    }//GEN-LAST:event_showProductDetail1

    private void showProductDetail2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProductDetail2
        DetailBook detailBook = new DetailBook();
        detailBook.openProductDetailUi(idBook2);  
    }//GEN-LAST:event_showProductDetail2

    private void showProductDetail3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProductDetail3
        DetailBook detailBook = new DetailBook();
        detailBook.openProductDetailUi(idBook3);  
    }//GEN-LAST:event_showProductDetail3

    private void showProductDetail4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProductDetail4
        DetailBook detailBook = new DetailBook();
        detailBook.openProductDetailUi(idBook4);   
    }//GEN-LAST:event_showProductDetail4

    private void cartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartButtonMouseClicked
        CartBook cart = new CartBook();
        if (!User.getName().equals("")){
            showCartUi(cart);
        }
        else {
            showMessageLogin();
        }
        
    }//GEN-LAST:event_cartButtonMouseClicked

    public void showCartUi(CartBook cart) {
        cart.setVisible(true);
    }

    public void showMessageLogin() throws HeadlessException {
        JOptionPane.showMessageDialog(null, "Please Login.");
    }

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel Banner1;
    private javax.swing.JLabel allBookButton;
    private javax.swing.JLabel background;
    private static javax.swing.JLabel banner;
    private javax.swing.JLabel banner1;
    private javax.swing.JLabel banner2;
    private javax.swing.JLabel banner3;
    private javax.swing.JLabel banner3Label;
    private javax.swing.JPanel blackTab;
    private javax.swing.JLabel bookImg1;
    private javax.swing.JLabel bookImg2;
    private javax.swing.JLabel bookImg3;
    private javax.swing.JLabel bookImg4;
    private javax.swing.JLabel bookName1;
    private javax.swing.JLabel bookName2;
    private javax.swing.JLabel bookName3;
    private javax.swing.JLabel bookName4;
    private javax.swing.JLabel cartButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel logInButton;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel priceBook1;
    private javax.swing.JLabel priceBook2;
    private javax.swing.JLabel priceBook3;
    private javax.swing.JLabel priceBook4;
    private javax.swing.JLabel recommendBook;
    private javax.swing.JLabel registerButton;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> searchBox;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField searchLeft;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchRight;
    private javax.swing.JLabel searchText;
    private javax.swing.JLabel shopIcon;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
    

    void setUser(String check) {
        User.setUser(userField.getText(), passField.getText(), check);
        statusLabel.setText(check);
        statusLabel.setVisible(true);
        userLabel.setVisible(false);
        userField.setVisible(false);
        passLabel.setVisible(false);
        passField.setVisible(false);

    }

    void time() {
        Timer myTimer;
        timer = 1;
        myTimer = new java.util.Timer();

        myTimer.schedule(new TimerTask() {
            public void run() {
                showBanner();       
            }
        }, 0, 6000);
    }

    void showBanner() {
        timesec++;
        if ( timesec == 3 ) {
            banner.setIcon(new javax.swing.ImageIcon(".\\src\\Pic\\Ban1.jpg"));
        } 
        else if ( timesec == 2 ) {
            banner.setIcon(new javax.swing.ImageIcon(".\\src\\Pic\\Ban2.jpg"));
        } 
        else {
            banner.setIcon(new javax.swing.ImageIcon(".\\src\\Pic\\NewBook.jpg"));
        }

        if ( timesec == 3 ) {
            timesec = 0;
        }
    }

    void showBook() {
        
        for ( int i = 1 ; i < 5 ; i++ ) {
            
            SearchBookService.getBook(i);
            
            if ( i == 1 ) {       
                ImageIcon icon = new ImageIcon(".\\src\\Pic\\Book\\" + Book.getId() + ".jpg");
                Image scaleImage = icon.getImage().getScaledInstance(116, 171, Image.SCALE_DEFAULT);
                bookImg1.setIcon(new javax.swing.ImageIcon(scaleImage));
                bookName1.setText(Book.getName());
                priceBook1.setText("Price : " + Book.getPrice());
                
            }
            else if ( i == 2 ) {          
                ImageIcon icon = new ImageIcon(".\\src\\Pic\\Book\\" + Book.getId() + ".jpg");
                Image scaleImage = icon.getImage().getScaledInstance(116, 171, Image.SCALE_DEFAULT);
                bookImg2.setIcon(new javax.swing.ImageIcon(scaleImage));
                bookName2.setText(Book.getName());
                priceBook2.setText("Price : " + Book.getPrice());
            }
            else if ( i == 3 ) {         
                ImageIcon icon = new ImageIcon(".\\src\\Pic\\Book\\" + Book.getId() + ".jpg");
                Image scaleImage = icon.getImage().getScaledInstance(116, 171, Image.SCALE_DEFAULT);
                bookImg3.setIcon(new javax.swing.ImageIcon(scaleImage)); 
                bookName3.setText(Book.getName());
                priceBook3.setText("Price : " + Book.getPrice());
            }
            else if ( i == 4 ) {          
                ImageIcon icon = new ImageIcon(".\\src\\Pic\\Book\\" + Book.getId() + ".jpg");
                Image scaleImage = icon.getImage().getScaledInstance(116, 171, Image.SCALE_DEFAULT);
                bookImg4.setIcon(new javax.swing.ImageIcon(scaleImage));  
                bookName4.setText(Book.getName());
                priceBook4.setText("Price : " + Book.getPrice());
            }

        }
    }

}
